spring:
  redis:
    database: 15
    host: 127.0.0.1
    port: 1005
    timeout: 43200000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000