server:
  port: 2008
spring:
  application:
    name: service-provider

#Eureka配置
eureka:
  instance:
    instance-id: 127.0.0.1:2008 #注册的ID
    prefer-ip-address: true #是否将IP注册到eureka, 否则将主机名注册到eureka
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka/

